import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({

  // ── Root ────────────────────────────────────────────────
  container: {
    flex: 1,
    backgroundColor: '#f8f7f4',
  },
  mainWrapper: {
    flex: 1,
    backgroundColor: '#f8f7f4',
    position: 'relative',
  },
  dashboardArea: {
    flex: 1,
    backgroundColor: '#f8f7f4',
  },

  // ── Header (same variables as DashboardScreen) ──────────
  header: {
    height: 58,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
    paddingHorizontal: 18,
    backgroundColor: '#ffffff',
  },
  menuButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuButtonText: {
    fontSize: 30,
    color: '#b47a00',
    fontWeight: '900',
    lineHeight: 34,
  },
  headerTitle: {
    flex: 1,
    marginLeft: 12,
    fontSize: 22,
    fontWeight: '900',
    color: '#1f1f1f',
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
  },

  // ── Scroll ──────────────────────────────────────────────
  scrollArea: {
    flex: 1,
  },
  scrollContent: {
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 42,
  },

  // ── Top row ─────────────────────────────────────────────
  topRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 10,
    alignItems: 'stretch',
  },
  statBox: {
    flex: 1,
    flexBasis: '47%',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e4cf88',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    justifyContent: 'center',
  },
  statLabel: {
    fontSize: 10,
    color: '#888888',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
    fontWeight: '600',
  },
  statValue: {
    fontSize: 22,
    fontWeight: '900',
    color: '#b47a00',
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
    marginTop: 2,
  },
  bookCard: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e4cf88',
    borderRadius: 10,
    padding: 11,
    marginBottom: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  bookCardLeft: {
    flex: 1,
  },
  bookCardTitle: {
    color: '#1f1f1f',
    fontSize: 13,
    fontWeight: '700',
  },
  bookCardSub: {
    color: '#888888',
    fontSize: 10,
    marginTop: 3,
    fontWeight: '500',
  },
  bookCardArrow: {
    color: '#c98904',
    fontSize: 18,
    marginLeft: 8,
  },

  // ── Filter chips ────────────────────────────────────────
  filterRow: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 14,
    alignItems: 'center',
  },
  filterChip: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#dddddd',
    paddingVertical: 5,
    paddingHorizontal: 12,
    borderRadius: 999,
  },
  filterChipActive: {
    backgroundColor: '#c98904',
    borderColor: '#c98904',
  },
  filterChipText: {
    fontSize: 11,
    color: '#555555',
    fontWeight: '600',
  },
  filterChipTextActive: {
    color: '#ffffff',
    fontWeight: '700',
  },
  policyIconButton: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#fff7df',
    borderWidth: 1,
    borderColor: '#d9aa25',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 2,
  },
  policyIconText: {
    color: '#b47a00',
    fontSize: 16,
    fontWeight: '900',
    lineHeight: 18,
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
  },

  // ── Appointment tab navigation ──────────────────────────
  appointmentTabBar: {
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e4cf88',
    borderRadius: 12,
    padding: 4,
    marginBottom: 16,
  },
  appointmentTab: {
    flex: 1,
    minHeight: 44,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 7,
  },
  appointmentTabActive: {
    backgroundColor: '#c98904',
  },
  appointmentTabText: {
    fontSize: 13,
    color: '#777777',
    fontWeight: '800',
  },
  appointmentTabTextActive: {
    color: '#ffffff',
  },
  appointmentTabCount: {
    minWidth: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: '#f8edcb',
    color: '#8a650e',
    textAlign: 'center',
    textAlignVertical: 'center',
    fontSize: 11,
    fontWeight: '900',
    overflow: 'hidden',
    paddingTop: Platform.OS === 'ios' ? 4 : 2,
  },
  appointmentTabCountActive: {
    backgroundColor: '#ffffff',
    color: '#b47a00',
  },

  // ── Loading / empty ─────────────────────────────────────
  loadingText: {
    fontSize: 13,
    color: '#888888',
    textAlign: 'center',
    paddingVertical: 40,
    fontWeight: '600',
  },
  emptyState: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#eeeeee',
    borderRadius: 10,
    padding: 24,
    alignItems: 'center',
  },
  emptyText: {
    fontSize: 12,
    color: '#888888',
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 20,
  },

  // ── Appointment sections ────────────────────────────────
  appointmentSection: {
    marginBottom: 18,
  },
  appointmentSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
    marginTop: 4,
  },
  appointmentSectionTitle: {
    fontSize: 15,
    fontWeight: '900',
    color: '#1f1f1f',
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
  },
  appointmentSectionCount: {
    minWidth: 26,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#fdf3df',
    color: '#8a650e',
    borderWidth: 1,
    borderColor: '#e4cf88',
    textAlign: 'center',
    textAlignVertical: 'center',
    fontSize: 12,
    fontWeight: '900',
    overflow: 'hidden',
    paddingTop: Platform.OS === 'ios' ? 4 : 2,
  },
  sectionEmptyBox: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#eeeeee',
    borderRadius: 10,
    paddingVertical: 14,
    paddingHorizontal: 12,
    marginBottom: 8,
  },
  sectionEmptyText: {
    fontSize: 12,
    color: '#888888',
    fontWeight: '600',
    textAlign: 'center',
    lineHeight: 18,
  },

  // ── Month label ─────────────────────────────────────────
  monthLabel: {
    fontSize: 10,
    fontWeight: '700',
    color: '#888888',
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: 7,
    marginTop: 2,
  },

  // ── Appointment card ────────────────────────────────────
  apptCard: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#eeeeee',
    borderRadius: 10,
    padding: 12,
    marginBottom: 8,
  },
  apptCardNext: {
    borderLeftWidth: 3,
    borderLeftColor: '#c98904',
  },
  nextPillWrap: {
    marginBottom: 6,
  },
  nextPill: {
    alignSelf: 'flex-start',
    backgroundColor: '#fdf3df',
    color: '#8a650e',
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    paddingVertical: 2,
    paddingHorizontal: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#e4cf88',
    overflow: 'hidden',
  },
  apptDatetime: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1f1f1f',
    marginBottom: 2,
  },
  apptService: {
    fontSize: 13,
    fontWeight: '600',
    color: '#333333',
    marginTop: 2,
  },
  apptStatus: {
    alignSelf: 'flex-start',
    marginTop: 7,
    backgroundColor: '#fdf3df',
    color: '#8a650e',
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 999,
    overflow: 'hidden',
  },
  apptStatusCompleted: {
    backgroundColor: '#e7f7ed',
    color: '#276749',
  },
  apptStatusCancelled: {
    backgroundColor: '#f8d7da',
    color: '#842029',
  },
  apptStatusMissed: {
    backgroundColor: '#feebc8',
    color: '#9c4221',
  },
  paymentTracker: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#fafafa',
    borderWidth: 1,
    borderColor: '#eeeeee',
    borderRadius: 8,
    padding: 9,
    marginTop: 9,
  },
  paymentTrackerDot: {
    width: 9,
    height: 9,
    borderRadius: 999,
    backgroundColor: '#b7b7b7',
    marginTop: 4,
    marginRight: 8,
  },
  paymentTrackerDotVerified: {
    backgroundColor: '#2f855a',
  },
  paymentTrackerDotPending: {
    backgroundColor: '#c98904',
  },
  paymentTrackerDotWaiting: {
    backgroundColor: '#888888',
  },
  paymentTrackerDotRejected: {
    backgroundColor: '#993c1d',
  },
  paymentTrackerTextArea: {
    flex: 1,
  },
  paymentTrackerTitle: {
    fontSize: 11,
    fontWeight: '800',
    color: '#1f1f1f',
  },
  paymentTrackerDetail: {
    fontSize: 10,
    color: '#777777',
    fontWeight: '600',
    lineHeight: 15,
    marginTop: 2,
  },

  // ── View details toggle ─────────────────────────────────
  viewDetailsBtn: {
    marginTop: 7,
  },
  viewDetailsBtnText: {
    fontSize: 11,
    color: '#b47a00',
    fontWeight: '600',
  },

  // ── Expanded details panel ──────────────────────────────
  detailsPanel: {
    backgroundColor: '#fafafa',
    borderWidth: 1,
    borderColor: '#eeeeee',
    borderRadius: 7,
    padding: 9,
    marginTop: 8,
  },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 4,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  detailLabel: {
    fontSize: 11,
    color: '#888888',
    fontWeight: '600',
  },
  detailVal: {
    fontSize: 11,
    color: '#1f1f1f',
    fontWeight: '700',
    textAlign: 'right',
  },

  // ── Action buttons ──────────────────────────────────────
  apptActions: {
    flexDirection: 'row',
    gap: 7,
    marginTop: 10,
    paddingTop: 9,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  btnReschedule: {
    flex: 1,
    backgroundColor: '#fdf3df',
    borderWidth: 1,
    borderColor: '#e4cf88',
    borderRadius: 7,
    paddingVertical: 7,
    alignItems: 'center',
  },
  btnRescheduleText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#7a4f00',
  },
  btnCancel: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#dddddd',
    borderRadius: 7,
    paddingVertical: 7,
    alignItems: 'center',
  },
  btnCancelDisabled: {
    backgroundColor: '#f1f1f1',
    borderColor: '#dddddd',
  },
  btnCancelText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#993c1d',
  },
  btnCancelTextDisabled: {
    color: '#a8a8a8',
  },
  btnReceipt: {
    flex: 1,
    backgroundColor: '#c98904',
    borderWidth: 1,
    borderColor: '#c98904',
    borderRadius: 7,
    paddingVertical: 7,
    alignItems: 'center',
  },
  btnReceiptDisabled: {
    backgroundColor: '#eeeeee',
    borderColor: '#dddddd',
  },
  btnReceiptText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#ffffff',
  },
  btnReceiptTextDisabled: {
    color: '#888888',
  },
  btnRating: {
    flex: 1,
    backgroundColor: '#1a6b3a',
    borderWidth: 1,
    borderColor: '#1a6b3a',
    borderRadius: 7,
    paddingVertical: 7,
    alignItems: 'center',
  },
  btnRatingText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#ffffff',
  },

  // ── Rating modal ─────────────────────────────────────────
  ratingLoadingBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 24,
    gap: 10,
  },
  ratingLoadingText: {
    fontSize: 13,
    color: '#888888',
    fontWeight: '600',
  },
  ratingChooseNote: {
    fontSize: 12,
    color: '#555555',
    fontWeight: '500',
    marginBottom: 14,
    lineHeight: 18,
  },
  ratingChooseBtn: {
    padding: 11,
    backgroundColor: '#1a6b3a',
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 8,
  },
  ratingChooseBtnText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#ffffff',
  },
  ratingChooseBtnOutline: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#1a6b3a',
  },
  ratingChooseBtnOutlineText: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1a6b3a',
  },
  ratingStarRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 10,
    marginTop: 4,
  },
  ratingStar: {
    fontSize: 32,
    color: '#dddddd',
  },
  ratingStarFilled: {
    color: '#c98904',
  },
  ratingLabelText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#8a650e',
    marginLeft: 6,
  },
  ratingLabelBelow: {
    fontSize: 12,
    fontWeight: '700',
    color: '#8a650e',
    marginBottom: 10,
    textAlign: 'center',
  },
  ratingFeedbackInput: {
    borderWidth: 1,
    borderColor: '#dddddd',
    borderRadius: 8,
    padding: 10,
    fontSize: 12,
    color: '#1f1f1f',
    minHeight: 72,
    textAlignVertical: 'top',
    marginBottom: 14,
    backgroundColor: '#fafafa',
  },
  ratingSubmitBtn: {
    backgroundColor: '#1a6b3a',
  },
  ratingViewFeedbackBox: {
    backgroundColor: '#f4f4f4',
    borderRadius: 8,
    padding: 10,
    marginBottom: 14,
  },
  ratingViewFeedbackText: {
    fontSize: 12,
    color: '#333333',
    lineHeight: 18,
  },
  ratingNoFeedbackText: {
    fontSize: 12,
    color: '#aaaaaa',
    fontStyle: 'italic',
    marginBottom: 14,
  },
  ratingSuccessBox: {
    alignItems: 'center',
    paddingVertical: 28,
  },
  ratingSuccessIcon: {
    fontSize: 42,
    color: '#1a6b3a',
    fontWeight: '900',
    marginBottom: 8,
  },
  ratingSuccessTitle: {
    fontSize: 18,
    fontWeight: '900',
    color: '#1f1f1f',
    marginBottom: 4,
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
  },
  ratingSuccessText: {
    fontSize: 12,
    color: '#555555',
    fontWeight: '500',
  },

  // ── Cancel modal ────────────────────────────────────────
  policyModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 24,
  },
  policyModalCard: {
    width: '100%',
    maxWidth: 360,
    backgroundColor: '#ffffff',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e4cf88',
    padding: 18,
    alignItems: 'center',
  },
  policyModalIcon: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#fff7df',
    borderWidth: 1,
    borderColor: '#d9aa25',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  policyModalIconText: {
    color: '#b47a00',
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 24,
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
  },
  policyModalTitle: {
    fontSize: 17,
    fontWeight: '900',
    color: '#1f1f1f',
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
    marginBottom: 8,
    textAlign: 'center',
  },
  policyModalBody: {
    fontSize: 12,
    color: '#4f5f76',
    lineHeight: 18,
    fontWeight: '500',
    textAlign: 'center',
    marginBottom: 16,
  },
  policyModalButton: {
    backgroundColor: '#c98904',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 28,
    minWidth: 112,
    alignItems: 'center',
  },
  policyModalButtonText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '800',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  modalSheet: {
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderTopWidth: 2,
    borderTopColor: '#c88a11',
    padding: 16,
    paddingBottom: 28,
  },
  modalHandle: {
    width: 32,
    height: 4,
    backgroundColor: '#e0ddd5',
    borderRadius: 999,
    alignSelf: 'center',
    marginBottom: 14,
  },
  modalTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1f1f1f',
    marginBottom: 4,
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
  },
  modalSub: {
    fontSize: 11,
    color: '#888888',
    fontWeight: '600',
    marginBottom: 12,
  },
  reasonOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    padding: 10,
    borderWidth: 1,
    borderColor: '#eeeeee',
    borderRadius: 8,
    marginBottom: 6,
    backgroundColor: '#ffffff',
  },
  reasonOptionSelected: {
    borderColor: '#c98904',
    backgroundColor: '#fdf3df',
  },
  reasonRadio: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: '#dddddd',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reasonRadioChecked: {
    borderColor: '#c98904',
    backgroundColor: '#c98904',
  },
  reasonRadioDot: {
    width: 5,
    height: 5,
    borderRadius: 999,
    backgroundColor: '#ffffff',
  },
  reasonText: {
    fontSize: 12,
    color: '#333333',
    fontWeight: '600',
    flex: 1,
  },
  reasonTextSelected: {
    color: '#8a650e',
  },
  modalActions: {
    flexDirection: 'row',
    gap: 8,
    marginTop: 12,
  },
  modalKeep: {
    flex: 1,
    padding: 10,
    borderWidth: 1,
    borderColor: '#dddddd',
    borderRadius: 8,
    alignItems: 'center',
    backgroundColor: '#ffffff',
  },
  modalKeepText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#555555',
  },
  modalConfirm: {
    flex: 1,
    padding: 10,
    backgroundColor: '#993c1d',
    borderRadius: 8,
    alignItems: 'center',
  },
  modalConfirmDisabled: {
    backgroundColor: '#dddddd',
  },
  modalConfirmText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#ffffff',
  },

  // ── Sidebar (same variables as DashboardScreen) ─────────
  sidebarOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 50,
    elevation: 50,
  },
  darkBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.42)',
  },
  sidebar: {
    position: 'absolute',
    top: 0,
    left: 0,
    bottom: 0,
    backgroundColor: '#ffffff',
    borderRightWidth: 1,
    borderRightColor: '#e0e0e0',
    paddingHorizontal: 20,
    paddingTop: 36,
    paddingBottom: 28,
    zIndex: 60,
    elevation: 60,
  },
  profileSection: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatarBox: {
    width: 52,
    height: 52,
    borderRadius: 11,
    backgroundColor: '#f0f0f0',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 13,
  },
  avatarText: {
    fontSize: 20,
    color: '#b47a00',
    fontWeight: '900',
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
  },
  profileTextArea: {
    flex: 1,
    justifyContent: 'center',
  },
  profileName: {
    fontSize: 18,
    color: '#b47a00',
    fontWeight: '900',
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
  },
  profileBranch: {
    fontSize: 13,
    color: '#8a650e',
    marginTop: 4,
  },
  sidebarLine: {
    height: 1,
    backgroundColor: '#e0e0e0',
    marginVertical: 14,
  },
  menuList: {
    flex: 1,
    //justifyContent: 'center',
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    marginBottom: 6,
    minHeight: 42,
  },
  activeMenuItem: {
    backgroundColor: '#fff8e7',
  },
  sidebarIcon: {
    width: 20,
    height: 20,
    marginRight: 16,
  },
  menuText: {
    flex: 1,
    fontSize: 15,
    color: '#b47a00',
    fontWeight: '700',
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  activeMenuText: {
    color: '#b47a00',
  },
  signOutSection: {
    marginTop: 'auto',
  },
  signOutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 8,
    minHeight: 42,
  },
  signOutText: {
    flex: 1,
    fontSize: 15,
    color: '#b47a00',
    fontWeight: '700',
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
});

export default styles;
