import { StyleSheet, Platform } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f7f4',
  },
  flex: {
    flex: 1,
  },

  header: {
    height: 58,
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1.2,
    borderBottomColor: '#c88a11',
    paddingHorizontal: 18,
    backgroundColor: '#ffffff',
  },
  backButton: {
    marginRight: 12,
    paddingVertical: 6,
    paddingRight: 4,
  },
  backButtonText: {
    color: '#b47a00',
    fontSize: 14,
    fontWeight: '800',
  },
  headerTitle: {
    color: '#1f1f1f',
    fontSize: 20,
    fontWeight: '900',
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
  },

  chatArea: {
    flex: 1,
  },
  chatContent: {
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 12,
  },

  // Bot greeting bubble
  botRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
    gap: 10,
  },
  botAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#1a365d',
    alignItems: 'center',
    justifyContent: 'center',
  },
  botAvatarText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  botBubble: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e4cf88',
    borderRadius: 14,
    borderTopLeftRadius: 4,
    paddingHorizontal: 14,
    paddingVertical: 12,
    shadowColor: '#c88a11',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 1,
  },
  botBubbleText: {
    color: '#1f1f1f',
    fontSize: 14,
    lineHeight: 22,
    fontWeight: '500',
  },

  // Loading / error in chat area
  loadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 16,
    paddingLeft: 4,
  },
  loadingText: {
    color: '#888888',
    fontSize: 13,
    fontWeight: '600',
  },
  error: {
    backgroundColor: '#fff3f0',
    color: '#993c1d',
    padding: 12,
    borderRadius: 8,
    fontSize: 13,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#f0c6b8',
    fontWeight: '600',
  },

  // Section cards
  sectionCard: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e4cf88',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 14,
    marginBottom: 12,
  },
  sectionLabel: {
    fontSize: 10,
    color: '#8a650e',
    textTransform: 'uppercase',
    letterSpacing: 1,
    fontWeight: '800',
    marginBottom: 10,
  },
  sectionSub: {
    fontSize: 12,
    color: '#888888',
    fontWeight: '500',
    marginBottom: 10,
    lineHeight: 18,
  },

  // Branch chips
  branchRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  branchChip: {
    backgroundColor: '#f8f7f4',
    borderWidth: 1,
    borderColor: '#e4cf88',
    paddingVertical: 7,
    paddingHorizontal: 15,
    borderRadius: 999,
  },
  branchChipActive: {
    backgroundColor: '#c98904',
    borderColor: '#c98904',
  },
  branchChipText: {
    fontSize: 12,
    color: '#8a650e',
    fontWeight: '800',
  },
  branchChipTextActive: {
    color: '#ffffff',
    fontWeight: '900',
  },

  // Service quick-pick chips
  chipGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  serviceChip: {
    backgroundColor: '#f8f7f4',
    borderWidth: 1,
    borderColor: '#d4b870',
    paddingVertical: 7,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  serviceChipActive: {
    backgroundColor: '#1a365d',
    borderColor: '#1a365d',
  },
  serviceChipText: {
    fontSize: 12,
    color: '#5a4a1e',
    fontWeight: '700',
  },
  serviceChipTextActive: {
    color: '#ffffff',
    fontWeight: '800',
  },

  // Bottom input area
  inputArea: {
    backgroundColor: '#ffffff',
    borderTopWidth: 1.2,
    borderTopColor: '#e4cf88',
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: Platform.OS === 'ios' ? 10 : 12,
  },
  chatInputHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    gap: 8,
  },
  inputAvatar: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: '#1a365d',
    alignItems: 'center',
    justifyContent: 'center',
  },
  inputAvatarText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.4,
  },
  inputLabel: {
    flex: 1,
    fontSize: 13,
    color: '#8a650e',
    fontWeight: '900',
    lineHeight: 18,
  },
  inputError: {
    color: '#993c1d',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 6,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1.2,
    borderColor: '#c88a11',
    borderRadius: 26,
    backgroundColor: '#fdfaf2',
    paddingLeft: 14,
    paddingRight: 8,
    paddingVertical: 7,
    shadowColor: '#c88a11',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 5,
    elevation: 2,
  },
  textInput: {
    flex: 1,
    paddingHorizontal: 0,
    paddingVertical: 8,
    paddingRight: 10,
    fontSize: 14,
    color: '#1f1f1f',
    minHeight: 42,
    maxHeight: 88,
    fontWeight: '500',
  },
  charCounter: {
    fontSize: 11,
    color: '#aaaaaa',
    fontWeight: '700',
  },
  sendButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: '#c98904',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendButtonDisabled: {
    opacity: 0.5,
  },
  sendButtonText: {
    color: '#ffffff',
    fontSize: 25,
    fontWeight: '900',
    lineHeight: 28,
  },
  inputHint: {
    color: '#8a650e',
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'right',
    marginTop: 8,
  },
  continueButtonHidden: {
    display: 'none',
  },
  continueButton: {
    backgroundColor: '#c98904',
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
  },
  continueButtonDisabled: {
    opacity: 0.5,
  },
  continueButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 0.3,
  },
  continueButtonRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },

  assistantPanel: {
    borderWidth: 1,
    borderColor: '#d6dde7',
    borderRadius: 14,
    overflow: 'hidden',
    backgroundColor: '#ffffff',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 3,
  },
  assistantPanelExpanded: {
    height: 640,
  },
  assistantHeader: {
    minHeight: 76,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#12a897',
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  assistantHeaderCompact: {
    minHeight: 58,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  assistantBotIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 2,
    borderColor: '#ffffff',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  assistantBotIconCompact: {
    width: 32,
    height: 32,
    borderRadius: 16,
    marginRight: 10,
  },
  assistantBotIconText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0.3,
  },
  assistantTitleBlock: {
    flex: 1,
  },
  assistantTitle: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: '700',
  },
  assistantTitleCompact: {
    fontSize: 18,
  },
  assistantStatusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 3,
  },
  onlineDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: '#20ee45',
    marginRight: 6,
  },
  assistantStatus: {
    color: '#20ee45',
    fontSize: 14,
    fontWeight: '700',
  },
  assistantIconButton: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 4,
  },
  assistantIconButtonText: {
    color: '#ffffff',
    fontSize: 24,
    fontWeight: '300',
    lineHeight: 28,
  },
  assistantMessages: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  assistantMessagesContent: {
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 14,
  },
  assistantMessagesContentCompact: {
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 8,
  },
  assistantMessageRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  assistantMessageRowUser: {
    justifyContent: 'flex-end',
  },
  assistantMiniAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#eef2f7',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 2,
  },
  assistantMiniAvatarText: {
    color: '#111827',
    fontSize: 9,
    fontWeight: '900',
  },
  assistantUserAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#eef0ff',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.14,
    shadowRadius: 8,
    elevation: 3,
  },
  assistantUserAvatarText: {
    color: '#32364f',
    fontSize: 14,
    fontWeight: '800',
  },
  assistantBubble: {
    maxWidth: '78%',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 5,
    elevation: 2,
  },
  assistantBubbleBot: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e8edf4',
  },
  assistantBubbleUser: {
    backgroundColor: '#eeecff',
  },
  assistantBubbleText: {
    color: '#2f3747',
    fontSize: 14,
    lineHeight: 21,
    fontWeight: '500',
  },
  assistantBubbleTextUser: {
    color: '#2f3146',
  },
  assistantBubbleTime: {
    color: '#758196',
    fontSize: 13,
    marginTop: 8,
    fontWeight: '500',
  },
  typingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 14,
  },
  typingBubble: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#f8fbfb',
    borderWidth: 1,
    borderColor: '#dbe7e7',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  typingText: {
    color: '#607080',
    fontSize: 13,
    fontWeight: '600',
  },
  assistantComposer: {
    minHeight: 110,
    flexDirection: 'row',
    alignItems: 'center',
    borderTopWidth: 1,
    borderTopColor: '#e0e5eb',
    backgroundColor: '#fbfcfd',
    paddingHorizontal: 18,
    paddingVertical: 16,
  },
  assistantComposerCompact: {
    minHeight: 76,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  assistantTextInput: {
    flex: 1,
    minHeight: 66,
    maxHeight: 96,
    borderWidth: 1,
    borderColor: '#b9c3d0',
    borderRadius: 7,
    backgroundColor: '#ffffff',
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: '#1f2937',
    fontSize: 16,
    fontWeight: '500',
  },
  assistantTextInputCompact: {
    minHeight: 48,
    maxHeight: 58,
    fontSize: 14,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  assistantSendButton: {
    width: 52,
    height: 52,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 10,
  },
  assistantSendButtonDisabled: {
    opacity: 0.5,
  },
  assistantSendButtonText: {
    color: '#111827',
    fontSize: 32,
    lineHeight: 36,
    fontWeight: '400',
  },

  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  modalBox: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    paddingHorizontal: 22,
    paddingVertical: 24,
    alignItems: 'center',
    borderTopWidth: 3,
    borderTopColor: '#c88a11',
    width: '100%',
  },
  modalIconRow: {
    marginBottom: 14,
  },
  modalIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#1a365d',
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalIconText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0.5,
  },
  modalTitle: {
    color: '#1f1f1f',
    fontSize: 16,
    fontWeight: '900',
    marginBottom: 10,
    textAlign: 'center',
    fontFamily: Platform.OS === 'ios' ? 'Georgia' : 'serif',
  },
  modalMessage: {
    color: '#555555',
    fontSize: 14,
    lineHeight: 21,
    textAlign: 'center',
    fontWeight: '500',
    marginBottom: 22,
  },
  modalOkButton: {
    backgroundColor: '#c98904',
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 10,
    alignItems: 'center',
    width: '100%',
  },
  modalOkButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '900',
  },
  modalSecondaryButton: {
    paddingVertical: 12,
    paddingHorizontal: 32,
    borderRadius: 10,
    alignItems: 'center',
    width: '100%',
    borderWidth: 1.2,
    borderColor: '#c88a11',
  },
  modalSecondaryButtonText: {
    color: '#8a650e',
    fontSize: 14,
    fontWeight: '800',
  },
});

export default styles;
