import { Link } from 'react-router-dom';
import { useEffect, useMemo, useState } from 'react';

import api from '../api/axios';
import { listPayments } from '../api/payments';
import { useAuth } from '../auth/AuthContext';
import AdminProfileMenu from '../components/AdminProfileMenu';
import NotificationUnreadBadge from '../components/NotificationUnreadBadge';
import createAdminTransactionsStyles from '../styles/AdminTransactions';
import clinicLogo from '../assets/adminImages/clinic-logo.png';

async function loadPdfTools() {
  const [{ default: jsPDF }, { default: autoTable }] = await Promise.all([
    import('jspdf'),
    import('jspdf-autotable'),
  ]);

  return { jsPDF, autoTable };
}

function formatPeso(value, options = {}) {
  const minimumFractionDigits = options.withDecimals ? 2 : 0;

  return `\u20B1${Number(value || 0).toLocaleString('en-PH', {
    minimumFractionDigits,
    maximumFractionDigits: 2,
  })}`;
}

function formatPdfPeso(value, options = {}) {
  const minimumFractionDigits = options.withDecimals ? 2 : 0;

  return `PHP ${Number(value || 0).toLocaleString('en-PH', {
    minimumFractionDigits,
    maximumFractionDigits: 2,
  })}`;
}

function formatDateParam(date) {
  return date.toISOString().slice(0, 10);
}

function getDateRange(range) {
  if (range === 'all') {
    return {};
  }

  const today = new Date();
  const from = new Date(today);

  if (range === '7') {
    from.setDate(today.getDate() - 6);
  } else if (range === '90') {
    from.setDate(today.getDate() - 89);
  } else {
    from.setDate(today.getDate() - 29);
  }

  return {
    from: formatDateParam(from),
    to: formatDateParam(today),
  };
}

function getPaymentAmount(payment) {
  return Number(payment.amount_received || payment.amount || 0);
}

function formatSource(source) {
  return source === 'staff_recorded' ? 'Front desk' : 'Patient app';
}

function formatStatus(status) {
  if (status === 'verified') return 'Paid';
  if (status === 'pending') return 'Pending';
  if (status === 'rejected') return 'Rejected';
  return status ? status.charAt(0).toUpperCase() + status.slice(1) : 'Unknown';
}

function getBranchCity(branch) {
  const address = branch?.address || '';
  const parts = address
    .split(',')
    .map((part) => part.trim())
    .filter(Boolean);

  if (parts.length > 0) {
    return parts[0];
  }

  return branch?.name || 'Branch';
}

function createFileName(title) {
  return (
    title
      .toLowerCase()
      .replace(/,/g, '')
      .replace(/\s+/g, '-')
      .replace(/[^a-z0-9-]/g, '') + '.pdf'
  );
}

function drawPdfHeader(doc, title, pageWidth, generatedText, rangeText) {
  doc.setFillColor(255, 248, 220);
  doc.rect(0, 0, pageWidth, 210, 'F');

  doc.setFillColor(139, 101, 8);
  doc.roundedRect(10, 10, pageWidth - 20, 30, 4, 4, 'F');

  doc.setFillColor(212, 175, 55);
  doc.rect(10, 37, pageWidth - 20, 2, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(17);
  doc.text(title, 16, 23);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.text('Smile Empress Dental Hub', 16, 31);

  doc.setTextColor(71, 85, 105);
  doc.setFontSize(9);
  doc.text(generatedText, pageWidth - 16, 48, { align: 'right' });
  doc.text(rangeText, 16, 48);
}

function drawPdfFooter(doc, pageWidth, pageHeight) {
  doc.setDrawColor(212, 175, 55);
  doc.setLineWidth(0.3);
  doc.line(10, pageHeight - 12, pageWidth - 10, pageHeight - 12);

  doc.setTextColor(100, 116, 139);
  doc.setFontSize(8);
  doc.text('Generated by ToothConnect', 10, pageHeight - 7);
  doc.text(`Page ${doc.internal.getCurrentPageInfo().pageNumber}`, pageWidth - 10, pageHeight - 7, {
    align: 'right',
  });
}

function AdminSidebar({ styles, openLogoutModal }) {
  return (
    <aside style={styles.sidebar}>
      <div style={styles.logo}>
        <img src={clinicLogo} alt="Clinic Logo" style={styles.logoImg} />
      </div>

      <nav style={styles.menu}>
        <Link to="/admin" style={styles.menuItem}>
          <i className="fi fi-rr-chart-histogram" style={styles.menuItemIcon}></i>
          <span style={styles.menuItemText}>Dashboard</span>
        </Link>

        <Link to="/adminPatients" style={styles.menuItem}>
          <i className="fi fi-rr-clipboard-user" style={styles.menuItemIcon}></i>
          <span style={styles.menuItemText}>Patient Records</span>
        </Link>

        <Link to="/adminEmployees" style={styles.menuItem}>
          <i className="fi fi-rr-stethoscope" style={styles.menuItemIcon}></i>
          <span style={styles.menuItemText}>Clinic Employee</span>
        </Link>

        <Link to="/adminInventory" style={styles.menuItem}>
          <i className="fi fi-rr-boxes" style={styles.menuItemIcon}></i>
          <span style={styles.menuItemText}>Inventory</span>
        </Link>

        <Link
          to="/adminTransactions"
          style={{ ...styles.menuItem, ...styles.menuItemActive }}
        >
          <i className="fi fi-rr-file-invoice-dollar" style={styles.menuItemIcon}></i>
          <span style={styles.menuItemText}>Transactions</span>
        </Link>

        <Link to="/adminLogs" style={styles.menuItem}>
          <i className="fi fi-rr-clipboard-list" style={styles.menuItemIcon}></i>
          <span style={styles.menuItemText}>Audit Logs</span>
        </Link>

        <Link to="/adminNotif" style={styles.menuItem}>
          <i className="fi fi-rr-bell" style={styles.menuItemIcon}></i>
          <span style={styles.menuItemText}>Notifications</span>
          <NotificationUnreadBadge />
        </Link>

        <Link to="/adminReports" style={styles.menuItem}>
          <i className="fi fi-rr-chart-line-up" style={styles.menuItemIcon}></i>
          <span style={styles.menuItemText}>Reports</span>
        </Link>

        <Link to="/adminSettings" style={styles.menuItem}>
          <i className="fi fi-rr-settings" style={styles.menuItemIcon}></i>
          <span style={styles.menuItemText}>Settings</span>
        </Link>
      </nav>

      <div style={styles.logoutSection}>
        <div style={styles.dropdownDivider}></div>

        <button
          type="button"
          style={{ ...styles.menuItem, ...styles.logoutItem, width: '100%' }}
          onClick={openLogoutModal}
        >
          <i className="fi fi-rr-sign-out-alt" style={styles.menuItemIcon}></i>
          <span style={styles.menuItemText}>Logout</span>
        </button>
      </div>
    </aside>
  );
}

export default function AdminTransactions() {
  const { user } = useAuth();
  const [screenWidth, setScreenWidth] = useState(
    typeof window !== 'undefined' ? window.innerWidth : 1200
  );
  const [payments, setPayments] = useState([]);
  const [branches, setBranches] = useState([]);
  const [branchFilter, setBranchFilter] = useState('');
  const [rangeFilter, setRangeFilter] = useState('30');
  const [statusFilter, setStatusFilter] = useState('');
  const [sourceFilter, setSourceFilter] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [showLogoutModal, setShowLogoutModal] = useState(false);
  const [messageModal, setMessageModal] = useState({ show: false, text: '' });
  const [currentPage, setCurrentPage] = useState(1);
  const rowsPerPage = 10;

  const isMobile = screenWidth <= 768;
  const isTablet = screenWidth > 768 && screenWidth <= 1200;
  const isSmallScreen = screenWidth <= 1200;
  const styles = createAdminTransactionsStyles({ isMobile, isTablet, isSmallScreen });
  const adminName = user?.name || user?.email || 'Admin';

  useEffect(() => {
    function handleResize() {
      setScreenWidth(window.innerWidth);
    }

    handleResize();
    window.addEventListener('resize', handleResize);

    return () => {
      window.removeEventListener('resize', handleResize);
    };
  }, []);

  useEffect(() => {
    const originalBodyMargin = document.body.style.margin;
    const originalBodyOverflowX = document.body.style.overflowX;
    const originalHtmlOverflowX = document.documentElement.style.overflowX;

    document.body.style.margin = '0';
    document.body.style.overflowX = 'hidden';
    document.documentElement.style.overflowX = 'hidden';

    return () => {
      document.body.style.margin = originalBodyMargin;
      document.body.style.overflowX = originalBodyOverflowX;
      document.documentElement.style.overflowX = originalHtmlOverflowX;
    };
  }, []);

  useEffect(() => {
    document.body.style.overflow = showLogoutModal || messageModal.show ? 'hidden' : '';

    return () => {
      document.body.style.overflow = '';
    };
  }, [showLogoutModal, messageModal.show]);

  useEffect(() => {
    async function loadBranches() {
      try {
        const res = await api.get('/auth/branches');
        setBranches(res.data.branches || []);
      } catch (err) {
        console.error('Failed to load branches', err);
        setBranches([]);
      }
    }

    loadBranches();
  }, []);

  useEffect(() => {
    let isCurrent = true;

    async function loadTransactions() {
      setLoading(true);
      setError('');

      try {
        const range = getDateRange(rangeFilter);
        const params = {
          ...range,
        };

        if (branchFilter) params.branch_id = branchFilter;
        if (statusFilter) params.status = statusFilter;
        if (sourceFilter) params.payment_source = sourceFilter;

        const data = await listPayments(params);

        if (isCurrent) {
          setPayments(data || []);
        }
      } catch (err) {
        console.error('Failed to load transactions', err);

        if (isCurrent) {
          setPayments([]);
          setError(err.response?.data?.message || 'Unable to load transactions.');
        }
      } finally {
        if (isCurrent) {
          setLoading(false);
        }
      }
    }

    loadTransactions();

    return () => {
      isCurrent = false;
    };
  }, [branchFilter, rangeFilter, statusFilter, sourceFilter]);

  const transactions = useMemo(() => {
    return payments.map((payment) => ({
      id: payment.id,
      appointment: `APT-${payment.appointment_id}`,
      branch: payment.branch_address || payment.branch_name || 'Branch not set',
      patient: payment.patient_name || 'Unnamed Patient',
      amountValue: getPaymentAmount(payment),
      amount: formatPeso(getPaymentAmount(payment)),
      pdfAmount: formatPdfPeso(getPaymentAmount(payment)),
      source: formatSource(payment.payment_source),
      status: formatStatus(payment.status),
      rawStatus: payment.status || '',
      rawSource: payment.payment_source || 'patient_upload',
      date: payment.paid_at || payment.recorded_at || payment.receipt_uploaded_at || payment.created_at,
      method: payment.payment_method || '',
      reference: payment.reference_number || '-',
    }));
  }, [payments]);

  const summary = useMemo(() => {
    const paidTransactions = transactions.filter((item) => item.rawStatus === 'verified');

    return {
      totalCollected: paidTransactions.reduce((sum, item) => sum + item.amountValue, 0),
      transactions: transactions.length,
      pending: transactions.filter((item) => item.rawStatus === 'pending').length,
      frontDesk: transactions.filter((item) => item.rawSource === 'staff_recorded').length,
    };
  }, [transactions]);

  const totalPages = Math.ceil(transactions.length / rowsPerPage);

  const paginatedTransactions = useMemo(() => {
    const start = (currentPage - 1) * rowsPerPage;
    const end = start + rowsPerPage;

    return transactions.slice(start, end);
  }, [transactions, currentPage]);

  useEffect(() => {
    setCurrentPage(1);
  }, [branchFilter, rangeFilter, statusFilter, sourceFilter]);

  useEffect(() => {
    if (totalPages > 0 && currentPage > totalPages) {
      setCurrentPage(totalPages);
    }
  }, [currentPage, totalPages]);

  function getStatusStyle(status) {
    if (status === 'Paid') return { ...styles.badge, ...styles.badgePaid };
    if (status === 'Pending') return { ...styles.badge, ...styles.badgePending };
    if (status === 'Rejected') return { ...styles.badge, ...styles.badgeRejected };
    return { ...styles.badge, ...styles.badgeDefault };
  }

  function getRangeLabel() {
    if (rangeFilter === '7') return 'Last 7 days';
    if (rangeFilter === '90') return 'Last 90 days';
    if (rangeFilter === 'all') return 'All dates';
    return 'Last 30 days';
  }

  function openLogoutModal() {
    setShowLogoutModal(true);
  }

  function closeLogoutModal() {
    setShowLogoutModal(false);
  }

  function handleLogout() {
    window.location.href = '/login';
  }

  function closeMessageModal() {
    setMessageModal({ show: false, text: '' });
  }

  function handleOverlayClick(event, callback) {
    if (event.target === event.currentTarget) {
      callback();
    }
  }

  function nextPage() {
    if (currentPage < totalPages) {
      setCurrentPage((page) => page + 1);
    }
  }

  function prevPage() {
    if (currentPage > 1) {
      setCurrentPage((page) => page - 1);
    }
  }

  async function exportToPDF() {
    if (transactions.length === 0) {
      setMessageModal({
        show: true,
        text: 'No transaction records available to export.',
      });
      return;
    }

    const { jsPDF, autoTable } = await loadPdfTools();
    const doc = new jsPDF('landscape', 'mm', 'a4');
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const generatedText = `Generated: ${new Date().toLocaleString('en-PH')}`;
    const rangeText = `Filter: ${getRangeLabel()}`;
    const title = 'Transactions Report';

    drawPdfHeader(doc, title, pageWidth, generatedText, rangeText);

    autoTable(doc, {
      body: [
        ['Total collected', formatPdfPeso(summary.totalCollected)],
        ['Transactions', String(summary.transactions)],
        ['Pending acknowledgement', String(summary.pending)],
        ['Front desk recorded', String(summary.frontDesk)],
      ],
      startY: 56,
      theme: 'grid',
      margin: { left: 10, right: 10 },
      styles: {
        font: 'helvetica',
        fontSize: 9,
        cellPadding: 3,
        textColor: [15, 23, 42],
        lineColor: [229, 231, 235],
        lineWidth: 0.25,
      },
      columnStyles: {
        0: { fontStyle: 'bold', fillColor: [255, 253, 242] },
      },
    });

    autoTable(doc, {
      head: [['Appointment', 'Branch', 'Patient', 'Amount', 'Reference/QR Number', 'Source', 'Status']],
      body: transactions.map((transaction) => [
        transaction.appointment,
        transaction.branch,
        transaction.patient,
        transaction.pdfAmount,
        transaction.reference,
        transaction.source,
        transaction.status,
      ]),
      startY: doc.lastAutoTable.finalY + 12,
      theme: 'grid',
      margin: { left: 10, right: 10 },
      styles: {
        font: 'helvetica',
        fontSize: 8,
        cellPadding: 2.8,
        textColor: [15, 23, 42],
        fillColor: [255, 255, 255],
        lineColor: [229, 231, 235],
        lineWidth: 0.25,
        overflow: 'linebreak',
      },
      headStyles: {
        fillColor: [212, 175, 55],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        halign: 'center',
      },
      alternateRowStyles: {
        fillColor: [255, 253, 242],
      },
      didDrawPage() {
        drawPdfFooter(doc, pageWidth, pageHeight);
      },
    });

    const totalPages = doc.internal.getNumberOfPages();

    for (let page = 1; page <= totalPages; page += 1) {
      doc.setPage(page);
      drawPdfFooter(doc, pageWidth, pageHeight);
    }

    doc.save(createFileName(title));
  }

  return (
    <div style={styles.page}>
      <AdminSidebar styles={styles} openLogoutModal={openLogoutModal} />

      <div style={styles.mainContainer}>
        <header style={styles.topHeader}>
          <div style={styles.headerActions}>
            <AdminProfileMenu styles={styles} adminName={adminName} />
          </div>
        </header>

        <main style={styles.mainContent}>
          <section style={styles.heroSection}>
            <div style={styles.heroContent}>
              <span style={styles.heroBadge}>Transactions</span>
              <h1 style={styles.heroTitle}>
                Monitor clinic payments and receipt records.
              </h1>
              <p style={styles.heroText}>
                Review collections, payment sources, references, and receipt
                acknowledgement status across clinic branches.
              </p>
            </div>

            <div style={styles.heroIconBox}>
              <i className="fi fi-rr-file-invoice-dollar" style={styles.heroIcon}></i>
            </div>
          </section>

          <section style={styles.filters}>
            <select
              value={branchFilter}
              onChange={(event) => setBranchFilter(event.target.value)}
              style={styles.filterSelect}
            >
              <option value="">All branches</option>
              {branches.map((branch) => (
                <option key={branch.id} value={branch.id}>
                  {getBranchCity(branch)}
                </option>
              ))}
            </select>

            <select
              value={rangeFilter}
              onChange={(event) => setRangeFilter(event.target.value)}
              style={styles.filterSelect}
            >
              <option value="30">Last 30 days</option>
              <option value="7">Last 7 days</option>
              <option value="90">Last 90 days</option>
              <option value="all">All dates</option>
            </select>

            <select
              value={statusFilter}
              onChange={(event) => setStatusFilter(event.target.value)}
              style={styles.filterSelect}
            >
              <option value="">All statuses</option>
              <option value="pending">Pending</option>
              <option value="verified">Paid</option>
              <option value="rejected">Rejected</option>
            </select>

            <select
              value={sourceFilter}
              onChange={(event) => setSourceFilter(event.target.value)}
              style={{ ...styles.filterSelect, ...styles.sourceFilter }}
            >
              <option value="">All sources</option>
              <option value="patient_upload">Patient app</option>
              <option value="staff_recorded">Front desk</option>
            </select>

            <button type="button" style={styles.pdfBtn} onClick={exportToPDF}>
              <i className="fi fi-rr-file-pdf"></i>
              PDF
            </button>
          </section>

          {error && <p style={styles.errorText}>{error}</p>}

          <section style={styles.summaryGrid}>
            <SummaryCard
              styles={styles}
              label="Total collected"
              value={formatPeso(summary.totalCollected)}
            />
            <SummaryCard styles={styles} label="Transactions" value={summary.transactions} />
            <SummaryCard
              styles={styles}
              label="Pending acknowledgement"
              value={summary.pending}
            />
            <SummaryCard
              styles={styles}
              label="Front desk recorded"
              value={summary.frontDesk}
            />
          </section>

          <section style={styles.tableWrap}>
            <div style={styles.tableHeader}>
              <h2 style={styles.tableTitle}>Transaction List</h2>
            </div>

            <div style={styles.tableWrapper}>
              <table style={styles.table}>
                <thead>
                  <tr>
                    <th style={styles.tableHead}>Appointment</th>
                    <th style={styles.tableHead}>Branch</th>
                    <th style={styles.tableHead}>Patient</th>
                    <th style={styles.tableHead}>Amount</th>
                    <th style={styles.tableHead}>Reference/QR Number</th>
                    <th style={styles.tableHead}>Source</th>
                    <th style={styles.tableHead}>Status</th>
                  </tr>
                </thead>

                <tbody>
                  {loading ? (
                    <tr>
                      <td colSpan={7} style={styles.emptyCell}>
                        Loading transactions...
                      </td>
                    </tr>
                  ) : transactions.length === 0 ? (
                    <tr>
                      <td colSpan={7} style={styles.emptyCell}>
                        No transactions found.
                      </td>
                    </tr>
                  ) : (
                    paginatedTransactions.map((transaction) => (
                      <tr key={transaction.id}>
                        <td style={styles.tableCell}>{transaction.appointment}</td>
                        <td style={styles.tableCell}>{transaction.branch}</td>
                        <td style={{ ...styles.tableCell, ...styles.tableCellStrong }}>
                          {transaction.patient}
                        </td>
                        <td style={styles.tableCell}>{transaction.amount}</td>
                        <td style={styles.tableCell}>{transaction.reference}</td>
                        <td style={styles.tableCell}>{transaction.source}</td>
                        <td style={styles.tableCell}>
                          <span style={getStatusStyle(transaction.status)}>
                            {transaction.status}
                          </span>
                        </td>
                      </tr>
                    ))
                  )}
                </tbody>
              </table>
            </div>

            <div style={styles.pagination}>
              <button
                type="button"
                onClick={prevPage}
                disabled={currentPage === 1}
                style={{
                  ...styles.pageBtn,
                  ...(currentPage === 1 ? styles.pageBtnDisabled : {}),
                }}
              >
                Prev
              </button>

              <span style={styles.pageInfo}>
                {transactions.length === 0
                  ? 'Page 0 of 0'
                  : `Page ${currentPage} of ${totalPages}`}
              </span>

              <button
                type="button"
                onClick={nextPage}
                disabled={currentPage >= totalPages}
                style={{
                  ...styles.pageBtn,
                  ...(currentPage >= totalPages ? styles.pageBtnDisabled : {}),
                }}
              >
                Next
              </button>
            </div>
          </section>
        </main>
      </div>

      {showLogoutModal && (
        <div
          style={styles.modal}
          onClick={(event) => handleOverlayClick(event, closeLogoutModal)}
        >
          <div style={styles.modalBox}>
            <h3 style={styles.modalTitle}>Confirm Logout</h3>
            <p style={styles.modalText}>Are you sure you want to logout?</p>

            <div style={{ display: 'flex', gap: 10, justifyContent: 'center' }}>
              <button
                type="button"
                style={{ ...styles.modalButton, background: '#eef2f7', color: '#0f172a' }}
                onClick={closeLogoutModal}
              >
                Cancel
              </button>
              <button type="button" style={styles.modalButton} onClick={handleLogout}>
                Logout
              </button>
            </div>
          </div>
        </div>
      )}

      {messageModal.show && (
        <div
          style={styles.modal}
          onClick={(event) => handleOverlayClick(event, closeMessageModal)}
        >
          <div style={styles.modalBox}>
            <h3 style={styles.modalTitle}>No Export Data</h3>
            <p style={styles.modalText}>{messageModal.text}</p>
            <button type="button" style={styles.modalButton} onClick={closeMessageModal}>
              OK
            </button>
          </div>
        </div>
      )}
    </div>
  );
}

function SummaryCard({ styles, label, value }) {
  return (
    <div style={styles.summaryCard}>
      <p style={styles.summaryLabel}>{label}</p>
      <h2 style={styles.summaryValue}>{value}</h2>
    </div>
  );
}
